export const APP_CONFIG_FILE = 'app.yml';

export const CONFIGURATION_SERVICE_TOKEN = Symbol('YML_CONFIG_SERVICE');

export const CONFIGURATION_TOKEN = 'YML_CONFIGURATION_TOKEN';
export const CONFIGURATION_LOADER = 'YML_CONFIGURATION_LOADER';

export const VALIDATED_ENV_PROPNAME = '_YML_PROCESS_ENV_VALIDATED';
